#-------------------------------------------------
#
# Project created by QtCreator 2017-11-23T18:43:18
#
#-------------------------------------------------

#QT       += core gui widgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = OrmasAdmin
TEMPLATE = app


SOURCES += CashBookListDlg.cpp \
	CashInfoDlg.cpp \
	ClcWagesDlg.cpp \
	CloseOfMonthDlg.cpp \
	CloseOfMonthInfoDlg.cpp \
	CreateAcсDlg.cpp \
    CreateAcсTpDlg.cpp \
	CreateAcctbDlg.cpp \
	CreateAccblEtrDlg.cpp \
	CreateAccblExpDlg.cpp \
	CreateAccblRepDlg.cpp \
    CreateAcsDlg.cpp \
    CreateAcsItemDlg.cpp \
	CreateAmGrDlg.cpp \
	CreateAmTypeDlg.cpp \
    CreateBlcDlg.cpp \
	CreateBrhDlg.cpp \
	CreateBrSAccDlg.cpp \
	CreateBrwDlg.cpp \
	CreateCARDlg.cpp \
	CreateCASHERDlg.cpp \
	CreateCbxDlg.cpp \
	CreateCERDlg.cpp \
    CreateCltDlg.cpp \
    CreateCmpDlg.cpp \
    CreateCOADlg.cpp \
	CreateConOthStDlg.cpp \
	CreateConOthStListDlg.cpp \
	CreateConPDlg.cpp \
    CreateConPListDlg.cpp \
    CreateConRDlg.cpp \
    CreateConRListDlg.cpp \
    CreateCurDlg.cpp \
	CreateDivAccDlg.cpp \
	CreateDivDlg.cpp \
    CreateEmpDlg.cpp \
	CreateEmpPrdDlg.cpp \
	CreateEtrDlg.cpp \
	CreateEtrRtDlg.cpp \
	CreateFxdAstDlg.cpp \
	CreateFxdAstOperDlg.cpp \
	CreateGrpDlg.cpp \
   	CreateInvDlg.cpp \
	CreateInveDlg.cpp \
    CreateInvListDlg.cpp \
	CreateJbpDlg.cpp \
    CreateJbsDlg.cpp \
	CreateLcnDlg.cpp \
	CreateLowValStockDlg.cpp \
    CreateMsrDlg.cpp \
	CreateNetCDlg.cpp \
    CreateOrdDlg.cpp \
    CreateOrdListDlg.cpp \
	CreateOrdRDlg.cpp \
    CreateOrdRListDlg.cpp \
	CreateOthStDlg.cpp \
	CreateOthSTypeDlg.cpp \
	CreatePcrDlg.cpp \
    CreatePhtDlg.cpp \
    CreatePmtDlg.cpp \
    CreatePosDlg.cpp \
	CreatePPlanDlg.cpp \
    CreatePPlanListDlg.cpp \
    CreatePrcDlg.cpp \
	CreatePrdBrnDlg.cpp \
	CreateProdConRDlg.cpp \
	CreateProdConRListDlg.cpp \
    CreatePrdTpDlg.cpp \
    CreateProdDlg.cpp \
    CreateProdnDlg.cpp \
	CreateProdnStockDlg.cpp \
    CreateProdnListDlg.cpp \
    CreatePspDlg.cpp \
	CreatePurDlg.cpp \
	CreateRcpOthStDlg.cpp \
	CreateRcpOthStListDlg.cpp \
	CreateRcpPDlg.cpp \
	CreateRcpPListDlg.cpp \
	CreateRelDlg.cpp \
    CreateRelTypeDlg.cpp \
    CreateRfdDlg.cpp \
    CreateRoleDlg.cpp \
    CreateRtrnDlg.cpp \
    CreateRtrnListDlg.cpp \
    CreateSlrDlg.cpp \
    CreateSlrTypeDlg.cpp \
	CreateSpecDlg.cpp \
    CreateSpecListDlg.cpp \
	CreateSplDlg.cpp \
    CreateSplListDlg.cpp \
	CreateStockDlg.cpp \
	CreateStockLmDlg.cpp \
	CreateStockTrDlg.cpp \
	CreateStockTrListDlg.cpp \
	CreateSAccDlg.cpp \
	CreateSAccLmDlg.cpp \
	CreateShrDlg.cpp \
    CreateStsDlg.cpp \
	CreateStsRuleDlg.cpp \
	CreateTaxDlg.cpp \
	CreateTmsDlg.cpp \
	CreateTrsDlg.cpp \
    CreateTrsListDlg.cpp \
    CreateUserDlg.cpp \
	CreateUserGrDlg.cpp \
    CreateWdwDlg.cpp \
	CreateWERDlg.cpp \
    CreateWOffDlg.cpp \
    CreateWOffListDlg.cpp \
	CreateWOffRDlg.cpp \
    CreateWOffRListDlg.cpp \
	CreateWrhDlg.cpp \
	CreateWrhTpDlg.cpp \
    DataForm.cpp \
	DocForm.cpp \
	GenerateAccDlg.cpp \
	GenerateAccRepDlg.cpp \
	GenerateAgentRepDlg.cpp \
    GenerateCmpBlcDlg.cpp \
	GenerateComRepDlg.cpp \
	GenerateDailySalesRepDlg.cpp \
    GenerateFinRepDlg.cpp \
	GenerateOneAccDlg.cpp \
    GenerateProfRepDlg.cpp \
    GenerateSalesRepDlg.cpp \
    GenerateSpecRepDlg.cpp \
	GenerateWrRepDlg.cpp \
	GenerateWTBSDlg.cpp \
	InfoForm.cpp \
	LoginForm.cpp \
	MainForm.cpp \
	ReworkRawDlg.cpp \
	ReportForm.cpp \
	SearchDlg.cpp \
    CreateAccDlg.cpp \
    CreateAccTpDlg.cpp

HEADERS  += AllDlgHeaders.h \
    CashBookListDlg.h \
	CashInfoDlg.h \
	ClcWagesDlg.h \
	CloseOfMonthDlg.h \
	CloseOfMonthInfoDlg.h \
	CreateAcсDlg.h \
    CreateAcсTpDlg.h \
	CreateAcctbDlg.h \
	CreateAccblEtrDlg.h \
	CreateAccblExpDlg.h \
	CreateAccblRepDlg.h \
    CreateAcsDlg.h \
    CreateAcsItemDlg.h \
	CreateAmGrDlg.h \
	CreateAmTypeDlg.h \
    CreateBlcDlg.h \
	CreateBrhDlg.h \
	CreateBrSAccDlg.h \
	CreateBrwDlg.h \
	CreateCARDlg.h \
	CreateCASHERDlg.h \
	CreateCbxDlg.h \
	CreateCERDlg.h \
    CreateCltDlg.h \
    CreateCmpDlg.h \
    CreateCOADlg.h \
	CreateConOthStDlg.h \
	CreateConOthStListDlg.h \
	CreateConPDlg.h \
    CreateConPListDlg.h \
    CreateConRDlg.h \
    CreateConRListDlg.h \
    CreateCurDlg.h \
	CreateDivAccDlg.h \
	CreateDivDlg.h \
    CreateEmpDlg.h \
	CreateEmpPrdDlg.h \
	CreateEtrDlg.h \
	CreateEtrRtDlg.h \
	CreateFxdAstDlg.h \
	CreateFxdAstOperDlg.h \
	CreateGrpDlg.h \
   	CreateInvDlg.h \
	CreateInveDlg.h \
    CreateInvListDlg.h \
	CreateJbpDlg.h \
    CreateJbsDlg.h \
	CreateLcnDlg.h \
	CreateLowValStockDlg.h \
    CreateMsrDlg.h \
	CreateNetCDlg.h \
    CreateOrdDlg.h \
    CreateOrdListDlg.h \
	CreateOrdRDlg.h \
    CreateOrdRListDlg.h \
	CreateOthStDlg.h \
	CreateOthSTypeDlg.h \
	CreatePcrDlg.h \
    CreatePhtDlg.h \
    CreatePmtDlg.h \
    CreatePosDlg.h \
	CreatePPlanDlg.h \
    CreatePPlanListDlg.h \
    CreatePrcDlg.h \
	CreatePrdBrnDlg.h \
	CreateProdConRDlg.h \
	CreateProdConRListDlg.h \
    CreatePrdTpDlg.h \
    CreateProdDlg.h \
    CreateProdnDlg.h \
	CreateProdnStockDlg.h \
    CreateProdnListDlg.h \
    CreatePspDlg.h \
	CreatePurDlg.h \
	CreateRcpOthStDlg.h \
	CreateRcpOthStListDlg.h \
	CreateRcpPDlg.h \
	CreateRcpPListDlg.h \
	CreateRelDlg.h \
    CreateRelTypeDlg.h \
    CreateRfdDlg.h \
    CreateRoleDlg.h \
    CreateRtrnDlg.h \
    CreateRtrnListDlg.h \
    CreateSlrDlg.h \
    CreateSlrTypeDlg.h \
	CreateSpecDlg.h \
    CreateSpecListDlg.h \
	CreateSplDlg.h \
    CreateSplListDlg.h \
	CreateStockDlg.h \
	CreateStockLmDlg.h \
	CreateStockTrDlg.h \
	CreateStockTrListDlg.h \
	CreateSAccDlg.h \
	CreateSAccLmDlg.h \
	CreateShrDlg.h \
    CreateStsDlg.h \
	CreateStsRuleDlg.h \
	CreateTaxDlg.h \
	CreateTmsDlg.h \
	CreateTrsDlg.h \
    CreateTrsListDlg.h \
    CreateUserDlg.h \
	CreateUserGrDlg.h \
    CreateWdwDlg.h \
	CreateWERDlg.h \
    CreateWOffDlg.h \
    CreateWOffListDlg.h \
	CreateWOffRDlg.h \
    CreateWOffRListDlg.h \
	CreateWrhDlg.h \
	CreateWrhTpDlg.h \
    DataForm.h \
	DocForm.h \
	GenerateAccDlg.h \
	GenerateAccRepDlg.h \
	GenerateAgentRepDlg.h \
    GenerateCmpBlcDlg.h \
	GenerateComRepDlg.h \
	GenerateDailySalesRepDlg.h \
    GenerateFinRepDlg.h \
	GenerateOneAccDlg.h \
    GenerateProfRepDlg.h \
    GenerateSalesRepDlg.h \
    GenerateSpecRepDlg.h \
	GenerateWrRepDlg.h \
	GenerateWTBSDlg.h \
	InfoForm.h \
	LoginForm.h \
	MainForm.h \
	ReworkRawDlg.h \
	ReportForm.h \
	SearchDlg.h \
    CreateAccDlg.h \
    CreateAccTpDlg.h

FORMS    += CashBookListDlg.ui \
	CashInfoDlg.ui \
	ClcWagesDlg.ui \
	CloseOfMonthDlg.ui \
	CloseOfMonthInfoDlg.ui \
	CreateAcсDlg.ui \
	CreateAcсTpDlg.ui \
	CreateAcctbDlg.ui \
	CreateAccblEtrDlg.ui \
	CreateAccblExpDlg.ui \
	CreateAccblRepDlg.ui \
    CreateAcsDlg.ui \
    CreateAcsItemDlg.ui \
	CreateAmGrDlg.ui \
	CreateAmTypeDlg.ui \
    CreateBlcDlg.ui \
	CreateBrhDlg.ui \
	CreateBrSAccDlg.ui \
	CreateBrwDlg.ui \
	CreateCARDlg.ui \
	CreateCASHERDlg.ui \
	CreateCbxDlg.ui \
	CreateCERDlg.ui \
    CreateCltDlg.ui \
    CreateCmpDlg.ui \
    CreateCOADlg.ui \
	CreateConOthStDlg.ui \
	CreateConOthStListDlg.ui \
	CreateConPDlg.ui \
    CreateConPListDlg.ui \
    CreateConRDlg.ui \
    CreateConRListDlg.ui \
    CreateCurDlg.ui \
	CreateDivAccDlg.ui \
	CreateDivDlg.ui \
    CreateEmpDlg.ui \
	CreateEmpPrdDlg.ui \
	CreateEtrDlg.ui \
	CreateEtrRtDlg.ui \
	CreateFxdAstDlg.ui \
	CreateFxdAstOperDlg.ui \
	CreateGrpDlg.ui \
   	CreateInvDlg.ui \
	CreateInveDlg.ui \
    CreateInvListDlg.ui \
	CreateJbpDlg.ui \
    CreateJbsDlg.ui \
	CreateLcnDlg.ui \
	CreateLowValStockDlg.ui \
    CreateMsrDlg.ui \
	CreateNetCDlg.ui \
    CreateOrdDlg.ui \
    CreateOrdListDlg.ui \
	CreateOrdRDlg.ui \
    CreateOrdRListDlg.ui \
	CreateOthStDlg.ui \
	CreateOthSTypeDlg.ui \
	CreatePcrDlg.ui \
    CreatePhtDlg.ui \
    CreatePmtDlg.ui \
    CreatePosDlg.ui \
	CreatePPlanDlg.ui \
    CreatePPlanListDlg.ui \
    CreatePrcDlg.ui \
	CreatePrdBrnDlg.ui \
	CreateProdConRDlg.ui \
	CreateProdConRListDlg.ui \
    CreatePrdTpDlg.ui \
    CreateProdDlg.ui \
    CreateProdnDlg.ui \
	CreateProdnStockDlg.ui \
    CreateProdnListDlg.ui \
    CreatePspDlg.ui \
	CreatePurDlg.ui \
	CreateRcpOthStDlg.ui \
	CreateRcpOthStListDlg.ui \
	CreateRcpPDlg.ui \
	CreateRcpPListDlg.ui \
	CreateRelDlg.ui \
    CreateRelTypeDlg.ui \
    CreateRfdDlg.ui \
    CreateRoleDlg.ui \
    CreateRtrnDlg.ui \
    CreateRtrnListDlg.ui \
    CreateSlrDlg.ui \
    CreateSlrTypeDlg.ui \
	CreateSpecDlg.ui \
    CreateSpecListDlg.ui \
	CreateSplDlg.ui \
    CreateSplListDlg.ui \
	CreateStockDlg.ui \
	CreateStockLmDlg.ui \
	CreateStockTrDlg.ui \
	CreateStockTrListDlg.ui \
	CreateSAccDlg.ui \
	CreateSAccLmDlg.ui \
	CreateShrDlg.ui \
    CreateStsDlg.ui \
	CreateStsRuleDlg.ui \
	CreateTaxDlg.ui \
	CreateTmsDlg.ui \
	CreateTrsDlg.ui \
    CreateTrsListDlg.ui \
    CreateUserDlg.ui \
	CreateUserGrDlg.ui \
    CreateWdwDlg.ui \
	CreateWERDlg.ui \
    CreateWOffDlg.ui \
    CreateWOffListDlg.ui \
	CreateWOffRDlg.ui \
    CreateWOffRListDlg.ui \
	CreateWrhDlg.ui \
	CreateWrhTpDlg.ui \
    DataForm.ui \
	DocForm.ui \
	GenerateAccDlg.ui \
	GenerateAccRepDlg.ui \
	GenerateAgentRepDlg.ui \
    GenerateCmpBlcDlg.ui \
	GenerateComRepDlg.ui \
	GenerateDailySalesRepDlg.ui \
    GenerateFinRepDlg.ui \
	GenerateOneAccDlg.ui \
    GenerateProfRepDlg.ui \
    GenerateSalesRepDlg.ui \
    GenerateSpecRepDlg.ui \
	GenerateWrRepDlg.ui \
	GenerateWTBSDlg.ui \
	InfoForm.ui \
	LoginForm.ui \
	MainForm.ui \
	ReworkRawDlg.ui \
	ReportForm.ui \
	SearchDlg.ui \
    CreateAccDlg.ui \
    CreateAccTpDlg.ui

DISTFILES += \
    ../../OrmasAdmin/OrmasAdmin/OrmasResource.rcc
	
TRANSLATIONS =  ormasadmin_ru.ts
