/********************************************************************************
** Form generated from reading UI file 'MainForm.ui'
**
** Created by: Qt User Interface Compiler version 5.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINFORM_H
#define UI_MAINFORM_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMdiArea>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionAllUsers;
    QAction *actionClients;
    QAction *actionEmployees;
    QAction *actionAccess;
    QAction *actionProductType;
    QAction *actionProducts;
    QAction *actionOrders;
    QAction *actionProductsList;
    QAction *actionOrderList;
    QAction *actionDeleteOrder;
    QAction *actionReturns;
    QAction *actionReturnList;
    QAction *actionDeleteReturn;
    QAction *actionCompany;
    QAction *actionCurrency;
    QAction *actionMeasure;
    QAction *actionLocation;
    QAction *actionRoles;
    QAction *actionStatus;
    QAction *actionAbout;
    QAction *actionProduction;
    QAction *actionAccessItems;
    QAction *actionPrices;
    QAction *actionProductionList;
    QAction *actionWriteOffs;
    QAction *actionWriteOffList;
    QAction *actionUserPhoto;
    QAction *actionProductPhoto;
    QAction *actionPosition;
    QAction *actionRelation;
    QAction *actionRelationType;
    QAction *actionBalances;
    QAction *actionSalary;
    QAction *actionSalaryType;
    QAction *actionPayments;
    QAction *actionPayroll;
    QAction *actionWithdrawal;
    QAction *actionRefund;
    QAction *actionPayslip;
    QAction *actionOrderRaws;
    QAction *actionStockTransfers;
    QAction *actionTransports;
    QAction *actionReceiptProducts;
    QAction *actionConsumptionRaws;
    QAction *actionWriteOffRaws;
    QAction *actionConsumptionProducts;
    QAction *actionStock;
    QAction *actionInventorization;
    QAction *actionSpecifications;
    QAction *actionSpecificationList;
    QAction *actionJobprice;
    QAction *actionJobsheet;
    QAction *actionPercentRate;
    QAction *actionTimesheet;
    QAction *actionAccounts;
    QAction *actionAccountType;
    QAction *actionChartOfAccounts;
    QAction *actionCompanyAccounts;
    QAction *actionEntry;
    QAction *actionNetCost;
    QAction *actionProductionPlan;
    QAction *actionProductionPlanList;
    QAction *actionSpoilage;
    QAction *actionSpoilageList;
    QAction *actionPurveyors;
    QAction *actionGenerateAccounts;
    QAction *actionGenerateOneAccount;
    QAction *actionEntryRouting;
    QAction *actionCompanyEmployees;
    QAction *actionProductionStock;
    QAction *actionStatusRule;
    QAction *actionSubaccounts;
    QAction *actionProductionConsumeRaws;
    QAction *actionCompanyBalanceInfo;
    QAction *actionReworkRaws;
    QAction *actionCloseOfMonth;
    QAction *actionFinancialReport;
    QAction *actionCompanyBalance;
    QAction *actionDivision;
    QAction *actionCash;
    QAction *actionCashBookList;
    QAction *actionSpecificationReport;
    QAction *actionProfitability;
    QAction *actionSalesReport;
    QAction *actionAccountCard;
    QAction *actionCashboxEmployees;
    QAction *actionWarehouseEmployees;
    QAction *actionBranch;
    QAction *actionWarehouseType;
    QAction *actionWarehouse;
    QAction *actionCashbox;
    QAction *actionRawStock;
    QAction *actionProductStock;
    QAction *actionAccountables;
    QAction *actionBorrowers;
    QAction *actionCreditors;
    QAction *actionShareholders;
    QAction *actionEmployeeProducts;
    QAction *actionBranchProducts;
    QAction *actionWarehouseTurnover;
    QAction *actionFixedAssets;
    QAction *actionFixedAssetsOperation;
    QAction *actionInventory;
    QAction *actionAmortizeGroup;
    QAction *actionAmortizeType;
    QAction *actionDivisionAccounts;
    QAction *actionOtherStocks;
    QAction *actionLowValueStock;
    QAction *actionConsumeOthSt;
    QAction *actionReceiptOthSt;
    QAction *actionGroup;
    QAction *actionUserGroup;
    QAction *actionStockLimit;
    QAction *actionSubaccountLimit;
    QAction *actionDailySalesReport;
    QAction *actionAccountableReport;
    QAction *actionBranchSubaccounts;
    QAction *actionCommonReport;
    QAction *actionAgentReport;
    QAction *actionDailyAgentReport;
    QAction *actionABCAnalysis;
    QAction *actionProductAlalysis;
    QAction *actionRawMaterialsAnalysis;
    QAction *actionCash_analysis;
    QAction *actionFixedAssetsReport;
    QAction *actionWarehouseReport;
    QAction *actionPriceExtention;
    QAction *actionNetCostCoefficient;
    QAction *actionMulticurrency;
    QAction *actionCurrencyRate;
    QAction *actionReturnReport;
    QAction *actionAnalysisReport;
    QAction *actionExpeditorMonthlyReport;
    QWidget *centrWidget;
    QGridLayout *gridLayout;
    QMdiArea *mdiArea;
    QMenuBar *menuBar;
    QMenu *menuUsers;
    QMenu *menuProducts;
    QMenu *menuOrders;
    QMenu *menuReturns;
    QMenu *menuReferences;
    QMenu *menuHelp;
    QMenu *menuProductions;
    QMenu *menuWriteOffs;
    QMenu *menuAccountings;
    QMenu *menuStock;
    QMenu *menuCash;
    QMenu *menuReports;
    QMenu *menuFixedAssets;
    QMenu *menuAnalysis;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1059, 824);
        MainWindow->setMinimumSize(QSize(800, 600));
        MainWindow->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        actionAllUsers = new QAction(MainWindow);
        actionAllUsers->setObjectName(QStringLiteral("actionAllUsers"));
        actionClients = new QAction(MainWindow);
        actionClients->setObjectName(QStringLiteral("actionClients"));
        actionEmployees = new QAction(MainWindow);
        actionEmployees->setObjectName(QStringLiteral("actionEmployees"));
        actionAccess = new QAction(MainWindow);
        actionAccess->setObjectName(QStringLiteral("actionAccess"));
        actionProductType = new QAction(MainWindow);
        actionProductType->setObjectName(QStringLiteral("actionProductType"));
        actionProducts = new QAction(MainWindow);
        actionProducts->setObjectName(QStringLiteral("actionProducts"));
        actionOrders = new QAction(MainWindow);
        actionOrders->setObjectName(QStringLiteral("actionOrders"));
        actionProductsList = new QAction(MainWindow);
        actionProductsList->setObjectName(QStringLiteral("actionProductsList"));
        actionOrderList = new QAction(MainWindow);
        actionOrderList->setObjectName(QStringLiteral("actionOrderList"));
        actionDeleteOrder = new QAction(MainWindow);
        actionDeleteOrder->setObjectName(QStringLiteral("actionDeleteOrder"));
        actionReturns = new QAction(MainWindow);
        actionReturns->setObjectName(QStringLiteral("actionReturns"));
        actionReturnList = new QAction(MainWindow);
        actionReturnList->setObjectName(QStringLiteral("actionReturnList"));
        actionDeleteReturn = new QAction(MainWindow);
        actionDeleteReturn->setObjectName(QStringLiteral("actionDeleteReturn"));
        actionCompany = new QAction(MainWindow);
        actionCompany->setObjectName(QStringLiteral("actionCompany"));
        actionCurrency = new QAction(MainWindow);
        actionCurrency->setObjectName(QStringLiteral("actionCurrency"));
        actionMeasure = new QAction(MainWindow);
        actionMeasure->setObjectName(QStringLiteral("actionMeasure"));
        actionLocation = new QAction(MainWindow);
        actionLocation->setObjectName(QStringLiteral("actionLocation"));
        actionRoles = new QAction(MainWindow);
        actionRoles->setObjectName(QStringLiteral("actionRoles"));
        actionStatus = new QAction(MainWindow);
        actionStatus->setObjectName(QStringLiteral("actionStatus"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionProduction = new QAction(MainWindow);
        actionProduction->setObjectName(QStringLiteral("actionProduction"));
        actionAccessItems = new QAction(MainWindow);
        actionAccessItems->setObjectName(QStringLiteral("actionAccessItems"));
        actionPrices = new QAction(MainWindow);
        actionPrices->setObjectName(QStringLiteral("actionPrices"));
        actionProductionList = new QAction(MainWindow);
        actionProductionList->setObjectName(QStringLiteral("actionProductionList"));
        actionWriteOffs = new QAction(MainWindow);
        actionWriteOffs->setObjectName(QStringLiteral("actionWriteOffs"));
        actionWriteOffList = new QAction(MainWindow);
        actionWriteOffList->setObjectName(QStringLiteral("actionWriteOffList"));
        actionUserPhoto = new QAction(MainWindow);
        actionUserPhoto->setObjectName(QStringLiteral("actionUserPhoto"));
        actionProductPhoto = new QAction(MainWindow);
        actionProductPhoto->setObjectName(QStringLiteral("actionProductPhoto"));
        actionPosition = new QAction(MainWindow);
        actionPosition->setObjectName(QStringLiteral("actionPosition"));
        actionRelation = new QAction(MainWindow);
        actionRelation->setObjectName(QStringLiteral("actionRelation"));
        actionRelationType = new QAction(MainWindow);
        actionRelationType->setObjectName(QStringLiteral("actionRelationType"));
        actionBalances = new QAction(MainWindow);
        actionBalances->setObjectName(QStringLiteral("actionBalances"));
        actionSalary = new QAction(MainWindow);
        actionSalary->setObjectName(QStringLiteral("actionSalary"));
        actionSalaryType = new QAction(MainWindow);
        actionSalaryType->setObjectName(QStringLiteral("actionSalaryType"));
        actionPayments = new QAction(MainWindow);
        actionPayments->setObjectName(QStringLiteral("actionPayments"));
        actionPayroll = new QAction(MainWindow);
        actionPayroll->setObjectName(QStringLiteral("actionPayroll"));
        actionWithdrawal = new QAction(MainWindow);
        actionWithdrawal->setObjectName(QStringLiteral("actionWithdrawal"));
        actionRefund = new QAction(MainWindow);
        actionRefund->setObjectName(QStringLiteral("actionRefund"));
        actionPayslip = new QAction(MainWindow);
        actionPayslip->setObjectName(QStringLiteral("actionPayslip"));
        actionOrderRaws = new QAction(MainWindow);
        actionOrderRaws->setObjectName(QStringLiteral("actionOrderRaws"));
        actionStockTransfers = new QAction(MainWindow);
        actionStockTransfers->setObjectName(QStringLiteral("actionStockTransfers"));
        actionTransports = new QAction(MainWindow);
        actionTransports->setObjectName(QStringLiteral("actionTransports"));
        actionReceiptProducts = new QAction(MainWindow);
        actionReceiptProducts->setObjectName(QStringLiteral("actionReceiptProducts"));
        actionConsumptionRaws = new QAction(MainWindow);
        actionConsumptionRaws->setObjectName(QStringLiteral("actionConsumptionRaws"));
        actionWriteOffRaws = new QAction(MainWindow);
        actionWriteOffRaws->setObjectName(QStringLiteral("actionWriteOffRaws"));
        actionConsumptionProducts = new QAction(MainWindow);
        actionConsumptionProducts->setObjectName(QStringLiteral("actionConsumptionProducts"));
        actionStock = new QAction(MainWindow);
        actionStock->setObjectName(QStringLiteral("actionStock"));
        actionInventorization = new QAction(MainWindow);
        actionInventorization->setObjectName(QStringLiteral("actionInventorization"));
        actionSpecifications = new QAction(MainWindow);
        actionSpecifications->setObjectName(QStringLiteral("actionSpecifications"));
        actionSpecificationList = new QAction(MainWindow);
        actionSpecificationList->setObjectName(QStringLiteral("actionSpecificationList"));
        actionJobprice = new QAction(MainWindow);
        actionJobprice->setObjectName(QStringLiteral("actionJobprice"));
        actionJobsheet = new QAction(MainWindow);
        actionJobsheet->setObjectName(QStringLiteral("actionJobsheet"));
        actionPercentRate = new QAction(MainWindow);
        actionPercentRate->setObjectName(QStringLiteral("actionPercentRate"));
        actionTimesheet = new QAction(MainWindow);
        actionTimesheet->setObjectName(QStringLiteral("actionTimesheet"));
        actionAccounts = new QAction(MainWindow);
        actionAccounts->setObjectName(QStringLiteral("actionAccounts"));
        actionAccountType = new QAction(MainWindow);
        actionAccountType->setObjectName(QStringLiteral("actionAccountType"));
        actionChartOfAccounts = new QAction(MainWindow);
        actionChartOfAccounts->setObjectName(QStringLiteral("actionChartOfAccounts"));
        actionCompanyAccounts = new QAction(MainWindow);
        actionCompanyAccounts->setObjectName(QStringLiteral("actionCompanyAccounts"));
        actionEntry = new QAction(MainWindow);
        actionEntry->setObjectName(QStringLiteral("actionEntry"));
        actionNetCost = new QAction(MainWindow);
        actionNetCost->setObjectName(QStringLiteral("actionNetCost"));
        actionProductionPlan = new QAction(MainWindow);
        actionProductionPlan->setObjectName(QStringLiteral("actionProductionPlan"));
        actionProductionPlanList = new QAction(MainWindow);
        actionProductionPlanList->setObjectName(QStringLiteral("actionProductionPlanList"));
        actionSpoilage = new QAction(MainWindow);
        actionSpoilage->setObjectName(QStringLiteral("actionSpoilage"));
        actionSpoilageList = new QAction(MainWindow);
        actionSpoilageList->setObjectName(QStringLiteral("actionSpoilageList"));
        actionPurveyors = new QAction(MainWindow);
        actionPurveyors->setObjectName(QStringLiteral("actionPurveyors"));
        actionGenerateAccounts = new QAction(MainWindow);
        actionGenerateAccounts->setObjectName(QStringLiteral("actionGenerateAccounts"));
        actionGenerateOneAccount = new QAction(MainWindow);
        actionGenerateOneAccount->setObjectName(QStringLiteral("actionGenerateOneAccount"));
        actionEntryRouting = new QAction(MainWindow);
        actionEntryRouting->setObjectName(QStringLiteral("actionEntryRouting"));
        actionCompanyEmployees = new QAction(MainWindow);
        actionCompanyEmployees->setObjectName(QStringLiteral("actionCompanyEmployees"));
        actionProductionStock = new QAction(MainWindow);
        actionProductionStock->setObjectName(QStringLiteral("actionProductionStock"));
        actionStatusRule = new QAction(MainWindow);
        actionStatusRule->setObjectName(QStringLiteral("actionStatusRule"));
        actionSubaccounts = new QAction(MainWindow);
        actionSubaccounts->setObjectName(QStringLiteral("actionSubaccounts"));
        actionProductionConsumeRaws = new QAction(MainWindow);
        actionProductionConsumeRaws->setObjectName(QStringLiteral("actionProductionConsumeRaws"));
        actionCompanyBalanceInfo = new QAction(MainWindow);
        actionCompanyBalanceInfo->setObjectName(QStringLiteral("actionCompanyBalanceInfo"));
        actionReworkRaws = new QAction(MainWindow);
        actionReworkRaws->setObjectName(QStringLiteral("actionReworkRaws"));
        actionCloseOfMonth = new QAction(MainWindow);
        actionCloseOfMonth->setObjectName(QStringLiteral("actionCloseOfMonth"));
        actionFinancialReport = new QAction(MainWindow);
        actionFinancialReport->setObjectName(QStringLiteral("actionFinancialReport"));
        actionCompanyBalance = new QAction(MainWindow);
        actionCompanyBalance->setObjectName(QStringLiteral("actionCompanyBalance"));
        actionDivision = new QAction(MainWindow);
        actionDivision->setObjectName(QStringLiteral("actionDivision"));
        actionCash = new QAction(MainWindow);
        actionCash->setObjectName(QStringLiteral("actionCash"));
        actionCashBookList = new QAction(MainWindow);
        actionCashBookList->setObjectName(QStringLiteral("actionCashBookList"));
        actionSpecificationReport = new QAction(MainWindow);
        actionSpecificationReport->setObjectName(QStringLiteral("actionSpecificationReport"));
        actionProfitability = new QAction(MainWindow);
        actionProfitability->setObjectName(QStringLiteral("actionProfitability"));
        actionSalesReport = new QAction(MainWindow);
        actionSalesReport->setObjectName(QStringLiteral("actionSalesReport"));
        actionAccountCard = new QAction(MainWindow);
        actionAccountCard->setObjectName(QStringLiteral("actionAccountCard"));
        actionCashboxEmployees = new QAction(MainWindow);
        actionCashboxEmployees->setObjectName(QStringLiteral("actionCashboxEmployees"));
        actionWarehouseEmployees = new QAction(MainWindow);
        actionWarehouseEmployees->setObjectName(QStringLiteral("actionWarehouseEmployees"));
        actionBranch = new QAction(MainWindow);
        actionBranch->setObjectName(QStringLiteral("actionBranch"));
        actionWarehouseType = new QAction(MainWindow);
        actionWarehouseType->setObjectName(QStringLiteral("actionWarehouseType"));
        actionWarehouse = new QAction(MainWindow);
        actionWarehouse->setObjectName(QStringLiteral("actionWarehouse"));
        actionCashbox = new QAction(MainWindow);
        actionCashbox->setObjectName(QStringLiteral("actionCashbox"));
        actionRawStock = new QAction(MainWindow);
        actionRawStock->setObjectName(QStringLiteral("actionRawStock"));
        actionProductStock = new QAction(MainWindow);
        actionProductStock->setObjectName(QStringLiteral("actionProductStock"));
        actionAccountables = new QAction(MainWindow);
        actionAccountables->setObjectName(QStringLiteral("actionAccountables"));
        actionBorrowers = new QAction(MainWindow);
        actionBorrowers->setObjectName(QStringLiteral("actionBorrowers"));
        actionCreditors = new QAction(MainWindow);
        actionCreditors->setObjectName(QStringLiteral("actionCreditors"));
        actionShareholders = new QAction(MainWindow);
        actionShareholders->setObjectName(QStringLiteral("actionShareholders"));
        actionEmployeeProducts = new QAction(MainWindow);
        actionEmployeeProducts->setObjectName(QStringLiteral("actionEmployeeProducts"));
        actionBranchProducts = new QAction(MainWindow);
        actionBranchProducts->setObjectName(QStringLiteral("actionBranchProducts"));
        actionWarehouseTurnover = new QAction(MainWindow);
        actionWarehouseTurnover->setObjectName(QStringLiteral("actionWarehouseTurnover"));
        actionFixedAssets = new QAction(MainWindow);
        actionFixedAssets->setObjectName(QStringLiteral("actionFixedAssets"));
        actionFixedAssetsOperation = new QAction(MainWindow);
        actionFixedAssetsOperation->setObjectName(QStringLiteral("actionFixedAssetsOperation"));
        actionInventory = new QAction(MainWindow);
        actionInventory->setObjectName(QStringLiteral("actionInventory"));
        actionAmortizeGroup = new QAction(MainWindow);
        actionAmortizeGroup->setObjectName(QStringLiteral("actionAmortizeGroup"));
        actionAmortizeType = new QAction(MainWindow);
        actionAmortizeType->setObjectName(QStringLiteral("actionAmortizeType"));
        actionDivisionAccounts = new QAction(MainWindow);
        actionDivisionAccounts->setObjectName(QStringLiteral("actionDivisionAccounts"));
        actionOtherStocks = new QAction(MainWindow);
        actionOtherStocks->setObjectName(QStringLiteral("actionOtherStocks"));
        actionLowValueStock = new QAction(MainWindow);
        actionLowValueStock->setObjectName(QStringLiteral("actionLowValueStock"));
        actionConsumeOthSt = new QAction(MainWindow);
        actionConsumeOthSt->setObjectName(QStringLiteral("actionConsumeOthSt"));
        actionReceiptOthSt = new QAction(MainWindow);
        actionReceiptOthSt->setObjectName(QStringLiteral("actionReceiptOthSt"));
        actionGroup = new QAction(MainWindow);
        actionGroup->setObjectName(QStringLiteral("actionGroup"));
        actionUserGroup = new QAction(MainWindow);
        actionUserGroup->setObjectName(QStringLiteral("actionUserGroup"));
        actionStockLimit = new QAction(MainWindow);
        actionStockLimit->setObjectName(QStringLiteral("actionStockLimit"));
        actionSubaccountLimit = new QAction(MainWindow);
        actionSubaccountLimit->setObjectName(QStringLiteral("actionSubaccountLimit"));
        actionDailySalesReport = new QAction(MainWindow);
        actionDailySalesReport->setObjectName(QStringLiteral("actionDailySalesReport"));
        actionAccountableReport = new QAction(MainWindow);
        actionAccountableReport->setObjectName(QStringLiteral("actionAccountableReport"));
        actionBranchSubaccounts = new QAction(MainWindow);
        actionBranchSubaccounts->setObjectName(QStringLiteral("actionBranchSubaccounts"));
        actionCommonReport = new QAction(MainWindow);
        actionCommonReport->setObjectName(QStringLiteral("actionCommonReport"));
        actionAgentReport = new QAction(MainWindow);
        actionAgentReport->setObjectName(QStringLiteral("actionAgentReport"));
        actionDailyAgentReport = new QAction(MainWindow);
        actionDailyAgentReport->setObjectName(QStringLiteral("actionDailyAgentReport"));
        actionABCAnalysis = new QAction(MainWindow);
        actionABCAnalysis->setObjectName(QStringLiteral("actionABCAnalysis"));
        actionProductAlalysis = new QAction(MainWindow);
        actionProductAlalysis->setObjectName(QStringLiteral("actionProductAlalysis"));
        actionRawMaterialsAnalysis = new QAction(MainWindow);
        actionRawMaterialsAnalysis->setObjectName(QStringLiteral("actionRawMaterialsAnalysis"));
        actionCash_analysis = new QAction(MainWindow);
        actionCash_analysis->setObjectName(QStringLiteral("actionCash_analysis"));
        actionFixedAssetsReport = new QAction(MainWindow);
        actionFixedAssetsReport->setObjectName(QStringLiteral("actionFixedAssetsReport"));
        actionWarehouseReport = new QAction(MainWindow);
        actionWarehouseReport->setObjectName(QStringLiteral("actionWarehouseReport"));
        actionPriceExtention = new QAction(MainWindow);
        actionPriceExtention->setObjectName(QStringLiteral("actionPriceExtention"));
        actionNetCostCoefficient = new QAction(MainWindow);
        actionNetCostCoefficient->setObjectName(QStringLiteral("actionNetCostCoefficient"));
        actionMulticurrency = new QAction(MainWindow);
        actionMulticurrency->setObjectName(QStringLiteral("actionMulticurrency"));
        actionCurrencyRate = new QAction(MainWindow);
        actionCurrencyRate->setObjectName(QStringLiteral("actionCurrencyRate"));
        actionReturnReport = new QAction(MainWindow);
        actionReturnReport->setObjectName(QStringLiteral("actionReturnReport"));
        actionAnalysisReport = new QAction(MainWindow);
        actionAnalysisReport->setObjectName(QStringLiteral("actionAnalysisReport"));
        actionExpeditorMonthlyReport = new QAction(MainWindow);
        actionExpeditorMonthlyReport->setObjectName(QStringLiteral("actionExpeditorMonthlyReport"));
        centrWidget = new QWidget(MainWindow);
        centrWidget->setObjectName(QStringLiteral("centrWidget"));
        gridLayout = new QGridLayout(centrWidget);
        gridLayout->setSpacing(0);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        mdiArea = new QMdiArea(centrWidget);
        mdiArea->setObjectName(QStringLiteral("mdiArea"));

        gridLayout->addWidget(mdiArea, 0, 0, 1, 1);

        MainWindow->setCentralWidget(centrWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1059, 26));
        menuUsers = new QMenu(menuBar);
        menuUsers->setObjectName(QStringLiteral("menuUsers"));
        menuUsers->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        menuProducts = new QMenu(menuBar);
        menuProducts->setObjectName(QStringLiteral("menuProducts"));
        menuOrders = new QMenu(menuBar);
        menuOrders->setObjectName(QStringLiteral("menuOrders"));
        menuReturns = new QMenu(menuBar);
        menuReturns->setObjectName(QStringLiteral("menuReturns"));
        menuReferences = new QMenu(menuBar);
        menuReferences->setObjectName(QStringLiteral("menuReferences"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        menuProductions = new QMenu(menuBar);
        menuProductions->setObjectName(QStringLiteral("menuProductions"));
        menuWriteOffs = new QMenu(menuBar);
        menuWriteOffs->setObjectName(QStringLiteral("menuWriteOffs"));
        menuAccountings = new QMenu(menuBar);
        menuAccountings->setObjectName(QStringLiteral("menuAccountings"));
        menuStock = new QMenu(menuBar);
        menuStock->setObjectName(QStringLiteral("menuStock"));
        menuCash = new QMenu(menuBar);
        menuCash->setObjectName(QStringLiteral("menuCash"));
        menuReports = new QMenu(menuBar);
        menuReports->setObjectName(QStringLiteral("menuReports"));
        menuFixedAssets = new QMenu(menuBar);
        menuFixedAssets->setObjectName(QStringLiteral("menuFixedAssets"));
        menuAnalysis = new QMenu(menuBar);
        menuAnalysis->setObjectName(QStringLiteral("menuAnalysis"));
        MainWindow->setMenuBar(menuBar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menuBar->addAction(menuUsers->menuAction());
        menuBar->addAction(menuProducts->menuAction());
        menuBar->addAction(menuOrders->menuAction());
        menuBar->addAction(menuReturns->menuAction());
        menuBar->addAction(menuWriteOffs->menuAction());
        menuBar->addAction(menuProductions->menuAction());
        menuBar->addAction(menuAccountings->menuAction());
        menuBar->addAction(menuFixedAssets->menuAction());
        menuBar->addAction(menuCash->menuAction());
        menuBar->addAction(menuStock->menuAction());
        menuBar->addAction(menuReports->menuAction());
        menuBar->addAction(menuReferences->menuAction());
        menuBar->addAction(menuAnalysis->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuUsers->addAction(actionAllUsers);
        menuUsers->addAction(actionClients);
        menuUsers->addAction(actionEmployees);
        menuUsers->addAction(actionPurveyors);
        menuUsers->addAction(actionAccountables);
        menuUsers->addAction(actionBorrowers);
        menuUsers->addAction(actionCreditors);
        menuUsers->addAction(actionShareholders);
        menuUsers->addAction(actionGroup);
        menuUsers->addAction(actionUserGroup);
        menuUsers->addSeparator();
        menuUsers->addAction(actionCompanyEmployees);
        menuUsers->addAction(actionCashboxEmployees);
        menuUsers->addAction(actionWarehouseEmployees);
        menuUsers->addSeparator();
        menuUsers->addAction(actionAccess);
        menuUsers->addAction(actionAccessItems);
        menuUsers->addAction(actionUserPhoto);
        menuUsers->addAction(actionPosition);
        menuProducts->addAction(actionProductType);
        menuProducts->addAction(actionProducts);
        menuProducts->addAction(actionProductPhoto);
        menuProducts->addAction(actionSpecifications);
        menuProducts->addAction(actionSpecificationList);
        menuProducts->addAction(actionPrices);
        menuProducts->addAction(actionPriceExtention);
        menuProducts->addAction(actionNetCost);
        menuProducts->addAction(actionEmployeeProducts);
        menuProducts->addAction(actionBranchProducts);
        menuProducts->addAction(actionOtherStocks);
        menuProducts->addAction(actionNetCostCoefficient);
        menuOrders->addAction(actionOrders);
        menuOrders->addAction(actionOrderList);
        menuReturns->addAction(actionReturns);
        menuReturns->addAction(actionReturnList);
        menuReferences->addAction(actionCompany);
        menuReferences->addAction(actionCurrency);
        menuReferences->addAction(actionMeasure);
        menuReferences->addAction(actionLocation);
        menuReferences->addAction(actionRoles);
        menuReferences->addAction(actionStatus);
        menuReferences->addAction(actionStatusRule);
        menuReferences->addAction(actionRelation);
        menuReferences->addAction(actionRelationType);
        menuReferences->addAction(actionDivision);
        menuReferences->addAction(actionBranch);
        menuReferences->addAction(actionWarehouseType);
        menuHelp->addAction(actionAbout);
        menuProductions->addAction(actionProduction);
        menuProductions->addAction(actionProductionList);
        menuProductions->addAction(actionProductionStock);
        menuProductions->addAction(actionProductionConsumeRaws);
        menuProductions->addAction(actionProductionPlan);
        menuProductions->addAction(actionProductionPlanList);
        menuProductions->addAction(actionJobprice);
        menuProductions->addAction(actionJobsheet);
        menuProductions->addAction(actionPercentRate);
        menuProductions->addAction(actionTimesheet);
        menuProductions->addAction(actionSpoilage);
        menuProductions->addAction(actionSpoilageList);
        menuProductions->addAction(actionReworkRaws);
        menuWriteOffs->addAction(actionWriteOffs);
        menuWriteOffs->addAction(actionWriteOffList);
        menuAccountings->addAction(actionBalances);
        menuAccountings->addAction(actionAccounts);
        menuAccountings->addAction(actionSubaccounts);
        menuAccountings->addAction(actionMulticurrency);
        menuAccountings->addAction(actionCurrencyRate);
        menuAccountings->addAction(actionSubaccountLimit);
        menuAccountings->addAction(actionGenerateOneAccount);
        menuAccountings->addAction(actionGenerateAccounts);
        menuAccountings->addSeparator();
        menuAccountings->addAction(actionSalary);
        menuAccountings->addAction(actionSalaryType);
        menuAccountings->addAction(actionPayroll);
        menuAccountings->addSeparator();
        menuAccountings->addAction(actionAccountType);
        menuAccountings->addAction(actionBranchSubaccounts);
        menuAccountings->addAction(actionDivisionAccounts);
        menuAccountings->addAction(actionChartOfAccounts);
        menuAccountings->addAction(actionCompanyAccounts);
        menuAccountings->addAction(actionEntry);
        menuAccountings->addAction(actionEntryRouting);
        menuAccountings->addAction(actionAccountableReport);
        menuAccountings->addAction(actionCloseOfMonth);
        menuAccountings->addSeparator();
        menuAccountings->addAction(actionWarehouse);
        menuAccountings->addAction(actionCashbox);
        menuStock->addAction(actionStock);
        menuStock->addAction(actionRawStock);
        menuStock->addAction(actionProductStock);
        menuStock->addAction(actionOrderRaws);
        menuStock->addAction(actionStockTransfers);
        menuStock->addAction(actionConsumptionRaws);
        menuStock->addAction(actionWriteOffRaws);
        menuStock->addAction(actionTransports);
        menuStock->addAction(actionReceiptProducts);
        menuStock->addAction(actionConsumptionProducts);
        menuStock->addAction(actionInventorization);
        menuStock->addAction(actionLowValueStock);
        menuStock->addAction(actionConsumeOthSt);
        menuStock->addAction(actionReceiptOthSt);
        menuStock->addAction(actionStockLimit);
        menuCash->addAction(actionCash);
        menuCash->addAction(actionPayments);
        menuCash->addAction(actionPayslip);
        menuCash->addAction(actionRefund);
        menuCash->addAction(actionWithdrawal);
        menuCash->addAction(actionCashBookList);
        menuReports->addAction(actionCompanyBalanceInfo);
        menuReports->addAction(actionFinancialReport);
        menuReports->addAction(actionCompanyBalance);
        menuReports->addSeparator();
        menuReports->addAction(actionSpecificationReport);
        menuReports->addAction(actionProfitability);
        menuReports->addAction(actionSalesReport);
        menuReports->addAction(actionAccountCard);
        menuReports->addAction(actionWarehouseTurnover);
        menuReports->addAction(actionDailySalesReport);
        menuReports->addAction(actionCommonReport);
        menuReports->addAction(actionExpeditorMonthlyReport);
        menuReports->addAction(actionAgentReport);
        menuReports->addSeparator();
        menuReports->addAction(actionFixedAssetsReport);
        menuReports->addAction(actionWarehouseReport);
        menuReports->addAction(actionReturnReport);
        menuReports->addAction(actionAnalysisReport);
        menuFixedAssets->addAction(actionFixedAssets);
        menuFixedAssets->addAction(actionFixedAssetsOperation);
        menuFixedAssets->addAction(actionInventory);
        menuFixedAssets->addAction(actionAmortizeGroup);
        menuFixedAssets->addAction(actionAmortizeType);
        menuAnalysis->addAction(actionABCAnalysis);
        menuAnalysis->addAction(actionProductAlalysis);
        menuAnalysis->addAction(actionRawMaterialsAnalysis);
        menuAnalysis->addAction(actionCash_analysis);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Ormas Admin Panel", 0));
        actionAllUsers->setText(QApplication::translate("MainWindow", "All users", 0));
        actionClients->setText(QApplication::translate("MainWindow", "Clients", 0));
        actionEmployees->setText(QApplication::translate("MainWindow", "Employees", 0));
        actionAccess->setText(QApplication::translate("MainWindow", "Access", 0));
        actionProductType->setText(QApplication::translate("MainWindow", "Products type", 0));
        actionProducts->setText(QApplication::translate("MainWindow", "Products", 0));
        actionOrders->setText(QApplication::translate("MainWindow", "Orders", 0));
        actionProductsList->setText(QApplication::translate("MainWindow", "Products list", 0));
        actionOrderList->setText(QApplication::translate("MainWindow", "Order details", 0));
        actionDeleteOrder->setText(QApplication::translate("MainWindow", "Delete order", 0));
        actionReturns->setText(QApplication::translate("MainWindow", "Returns", 0));
        actionReturnList->setText(QApplication::translate("MainWindow", "Retrun details", 0));
        actionDeleteReturn->setText(QApplication::translate("MainWindow", "Delete return", 0));
        actionCompany->setText(QApplication::translate("MainWindow", "Company", 0));
        actionCurrency->setText(QApplication::translate("MainWindow", "Currency", 0));
        actionMeasure->setText(QApplication::translate("MainWindow", "Measure", 0));
        actionLocation->setText(QApplication::translate("MainWindow", "Location", 0));
        actionRoles->setText(QApplication::translate("MainWindow", "Roles", 0));
        actionStatus->setText(QApplication::translate("MainWindow", "Status", 0));
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0));
        actionProduction->setText(QApplication::translate("MainWindow", "Production", 0));
        actionAccessItems->setText(QApplication::translate("MainWindow", "Access items", 0));
        actionPrices->setText(QApplication::translate("MainWindow", "Prices", 0));
        actionProductionList->setText(QApplication::translate("MainWindow", "Production details", 0));
        actionWriteOffs->setText(QApplication::translate("MainWindow", "Write-offs", 0));
        actionWriteOffList->setText(QApplication::translate("MainWindow", "Write-off details", 0));
        actionUserPhoto->setText(QApplication::translate("MainWindow", "User photo", 0));
        actionProductPhoto->setText(QApplication::translate("MainWindow", "Product photo", 0));
        actionPosition->setText(QApplication::translate("MainWindow", "Position", 0));
        actionRelation->setText(QApplication::translate("MainWindow", "Relation", 0));
        actionRelationType->setText(QApplication::translate("MainWindow", "Relation types", 0));
        actionBalances->setText(QApplication::translate("MainWindow", "Balances", 0));
        actionSalary->setText(QApplication::translate("MainWindow", "Salary", 0));
        actionSalaryType->setText(QApplication::translate("MainWindow", "Salary type", 0));
        actionPayments->setText(QApplication::translate("MainWindow", "Payments", 0));
        actionPayroll->setText(QApplication::translate("MainWindow", "Payroll", 0));
        actionWithdrawal->setText(QApplication::translate("MainWindow", "Withdrawal", 0));
        actionRefund->setText(QApplication::translate("MainWindow", "Refund", 0));
        actionPayslip->setText(QApplication::translate("MainWindow", "Payslip", 0));
        actionOrderRaws->setText(QApplication::translate("MainWindow", "Order raw materials", 0));
        actionStockTransfers->setText(QApplication::translate("MainWindow", "Stock transfer", 0));
        actionTransports->setText(QApplication::translate("MainWindow", "Transports", 0));
        actionReceiptProducts->setText(QApplication::translate("MainWindow", "Receipt products", 0));
        actionConsumptionRaws->setText(QApplication::translate("MainWindow", "Consumption raw materials", 0));
        actionWriteOffRaws->setText(QApplication::translate("MainWindow", "Write-off raw materials", 0));
        actionConsumptionProducts->setText(QApplication::translate("MainWindow", "Consumption products", 0));
        actionStock->setText(QApplication::translate("MainWindow", "Stock", 0));
        actionInventorization->setText(QApplication::translate("MainWindow", "Inventorization", 0));
        actionSpecifications->setText(QApplication::translate("MainWindow", "Specification", 0));
        actionSpecificationList->setText(QApplication::translate("MainWindow", "Specification details", 0));
        actionJobprice->setText(QApplication::translate("MainWindow", "Jobprice", 0));
        actionJobsheet->setText(QApplication::translate("MainWindow", "Jobsheet", 0));
        actionPercentRate->setText(QApplication::translate("MainWindow", "Percent rate", 0));
        actionTimesheet->setText(QApplication::translate("MainWindow", "Timesheet", 0));
        actionAccounts->setText(QApplication::translate("MainWindow", "Accounts", 0));
        actionAccountType->setText(QApplication::translate("MainWindow", "Account type", 0));
        actionChartOfAccounts->setText(QApplication::translate("MainWindow", "Chart of Accounts", 0));
        actionCompanyAccounts->setText(QApplication::translate("MainWindow", "Company accounts", 0));
        actionEntry->setText(QApplication::translate("MainWindow", "Entry", 0));
        actionNetCost->setText(QApplication::translate("MainWindow", "Net cost", 0));
        actionProductionPlan->setText(QApplication::translate("MainWindow", "Production plan", 0));
        actionProductionPlanList->setText(QApplication::translate("MainWindow", "Production plan details", 0));
        actionSpoilage->setText(QApplication::translate("MainWindow", "Spoilage", 0));
        actionSpoilageList->setText(QApplication::translate("MainWindow", "Spoilage details", 0));
        actionPurveyors->setText(QApplication::translate("MainWindow", "Purveyors", 0));
        actionGenerateAccounts->setText(QApplication::translate("MainWindow", "Generate accounts", 0));
        actionGenerateOneAccount->setText(QApplication::translate("MainWindow", "Generate one account", 0));
        actionEntryRouting->setText(QApplication::translate("MainWindow", "Entry routing", 0));
        actionCompanyEmployees->setText(QApplication::translate("MainWindow", "Company employees", 0));
        actionProductionStock->setText(QApplication::translate("MainWindow", "Production stock", 0));
        actionStatusRule->setText(QApplication::translate("MainWindow", "Status rule", 0));
        actionSubaccounts->setText(QApplication::translate("MainWindow", "Subaccounts", 0));
        actionProductionConsumeRaws->setText(QApplication::translate("MainWindow", "Consume raws", 0));
        actionCompanyBalanceInfo->setText(QApplication::translate("MainWindow", "Company balance info", 0));
        actionReworkRaws->setText(QApplication::translate("MainWindow", "Rework raws", 0));
        actionCloseOfMonth->setText(QApplication::translate("MainWindow", "Close of month", 0));
        actionFinancialReport->setText(QApplication::translate("MainWindow", "Financial report", 0));
        actionCompanyBalance->setText(QApplication::translate("MainWindow", "Company balance", 0));
        actionDivision->setText(QApplication::translate("MainWindow", "Division", 0));
        actionCash->setText(QApplication::translate("MainWindow", "Cash", 0));
        actionCashBookList->setText(QApplication::translate("MainWindow", "Cash book list", 0));
        actionSpecificationReport->setText(QApplication::translate("MainWindow", "Specification report", 0));
        actionProfitability->setText(QApplication::translate("MainWindow", "Profitability", 0));
        actionSalesReport->setText(QApplication::translate("MainWindow", "Sales report", 0));
        actionAccountCard->setText(QApplication::translate("MainWindow", "Account card", 0));
        actionCashboxEmployees->setText(QApplication::translate("MainWindow", "Cashbox employees", 0));
        actionWarehouseEmployees->setText(QApplication::translate("MainWindow", "Warehouse employees", 0));
        actionBranch->setText(QApplication::translate("MainWindow", "Branch", 0));
        actionWarehouseType->setText(QApplication::translate("MainWindow", "Warehouse types", 0));
        actionWarehouse->setText(QApplication::translate("MainWindow", "Warehouse", 0));
        actionCashbox->setText(QApplication::translate("MainWindow", "Cashbox", 0));
        actionRawStock->setText(QApplication::translate("MainWindow", "Raw stock", 0));
        actionProductStock->setText(QApplication::translate("MainWindow", "Product stock", 0));
        actionAccountables->setText(QApplication::translate("MainWindow", "Accountables", 0));
        actionBorrowers->setText(QApplication::translate("MainWindow", "Borrower", 0));
        actionCreditors->setText(QApplication::translate("MainWindow", "Creditor", 0));
        actionShareholders->setText(QApplication::translate("MainWindow", "Shareholders", 0));
        actionEmployeeProducts->setText(QApplication::translate("MainWindow", "Employeee products", 0));
        actionBranchProducts->setText(QApplication::translate("MainWindow", "Branch products", 0));
        actionWarehouseTurnover->setText(QApplication::translate("MainWindow", "Warehouse turnover", 0));
        actionFixedAssets->setText(QApplication::translate("MainWindow", "Fixed assets", 0));
        actionFixedAssetsOperation->setText(QApplication::translate("MainWindow", "Fixed assets operation", 0));
        actionInventory->setText(QApplication::translate("MainWindow", "Inventory", 0));
        actionAmortizeGroup->setText(QApplication::translate("MainWindow", "Amortize group", 0));
        actionAmortizeType->setText(QApplication::translate("MainWindow", "Amortize type", 0));
        actionDivisionAccounts->setText(QApplication::translate("MainWindow", "Division assounts", 0));
        actionOtherStocks->setText(QApplication::translate("MainWindow", "Other stocks", 0));
        actionLowValueStock->setText(QApplication::translate("MainWindow", "Low value stock", 0));
        actionConsumeOthSt->setText(QApplication::translate("MainWindow", "Consume other stocks", 0));
        actionReceiptOthSt->setText(QApplication::translate("MainWindow", "Receipt other stocks", 0));
        actionGroup->setText(QApplication::translate("MainWindow", "Group", 0));
        actionUserGroup->setText(QApplication::translate("MainWindow", "User group relation", 0));
        actionStockLimit->setText(QApplication::translate("MainWindow", "Stock limit", 0));
        actionSubaccountLimit->setText(QApplication::translate("MainWindow", "Subaccount limit", 0));
        actionDailySalesReport->setText(QApplication::translate("MainWindow", "Daily sales report", 0));
        actionAccountableReport->setText(QApplication::translate("MainWindow", "Accountable report", 0));
        actionBranchSubaccounts->setText(QApplication::translate("MainWindow", "Branch subaccounts", 0));
        actionCommonReport->setText(QApplication::translate("MainWindow", "Common report", 0));
        actionAgentReport->setText(QApplication::translate("MainWindow", "Agent report", 0));
        actionDailyAgentReport->setText(QApplication::translate("MainWindow", "Daily agent report", 0));
        actionABCAnalysis->setText(QApplication::translate("MainWindow", "ABC analysis", 0));
        actionProductAlalysis->setText(QApplication::translate("MainWindow", "Product and Net cost alalysis", 0));
        actionRawMaterialsAnalysis->setText(QApplication::translate("MainWindow", "Raw materials analysis", 0));
        actionCash_analysis->setText(QApplication::translate("MainWindow", "Cash analysis", 0));
        actionFixedAssetsReport->setText(QApplication::translate("MainWindow", "Fixed assets report", 0));
        actionWarehouseReport->setText(QApplication::translate("MainWindow", "Warehouse report", 0));
        actionPriceExtention->setText(QApplication::translate("MainWindow", "Price extention", 0));
        actionNetCostCoefficient->setText(QApplication::translate("MainWindow", "Net cost coefficient", 0));
        actionMulticurrency->setText(QApplication::translate("MainWindow", "Multicurrency", 0));
        actionCurrencyRate->setText(QApplication::translate("MainWindow", "Currency rate", 0));
        actionReturnReport->setText(QApplication::translate("MainWindow", "Return report", 0));
        actionAnalysisReport->setText(QApplication::translate("MainWindow", "Analysis report", 0));
        actionExpeditorMonthlyReport->setText(QApplication::translate("MainWindow", "Expeditor monthly report", 0));
        menuUsers->setTitle(QApplication::translate("MainWindow", "Users", 0));
        menuProducts->setTitle(QApplication::translate("MainWindow", "Products", 0));
        menuOrders->setTitle(QApplication::translate("MainWindow", "Orders", 0));
        menuReturns->setTitle(QApplication::translate("MainWindow", "Returns", 0));
        menuReferences->setTitle(QApplication::translate("MainWindow", "Reference", 0));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0));
        menuProductions->setTitle(QApplication::translate("MainWindow", "Production", 0));
        menuWriteOffs->setTitle(QApplication::translate("MainWindow", "Write-offs", 0));
        menuAccountings->setTitle(QApplication::translate("MainWindow", "Accounting", 0));
        menuStock->setTitle(QApplication::translate("MainWindow", "Stock", 0));
        menuCash->setTitle(QApplication::translate("MainWindow", "Cash", 0));
        menuReports->setTitle(QApplication::translate("MainWindow", "Reports", 0));
        menuFixedAssets->setTitle(QApplication::translate("MainWindow", "Fixed assets", 0));
        menuAnalysis->setTitle(QApplication::translate("MainWindow", "Analysis", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINFORM_H
